from typing import Literal

from pydantic import BaseModel
from strands import Agent

from config import MODEL_ID


class EvidenceItem(BaseModel):
    type: Literal[
        "invoice",
        "email",
        "transaction_history",
        "subscription_terms",
        "other",
    ]
    uri: str | None
    description: str


class DisputeMessageResult(BaseModel):
    message: str


class DisputeResult(BaseModel):
    case_id: str
    merchant_id: str
    user_id: str
    transaction_id: str

    claim_type: Literal[
        "price_hike",
        "duplicate_charge",
        "charge_after_cancellation",
        "other",
    ]

    requested_amount_usd: float
    currency: str

    message: str
    evidence: list[EvidenceItem]


SYSTEM_PROMPT = """
You are DisputeAgent.

Your job is to write a clear and professional billing dispute message
using only the anomaly analysis and evidence provided.

Possible claim types:

- price_hike
- duplicate_charge
- charge_after_cancellation
- other

For a PRICE_HIKE dispute:
- explain the historical expected amount
- explain the new amount
- request only the unjustified increase

For a DUPLICATE_CHARGE dispute:
- explain that two charges for the same subscription,
  merchant and amount occurred within an unusually short period
- identify the suspicious duplicate transaction when provided
- request a refund of the FULL duplicated charge
- do not describe the refund as a difference between prices

For a CHARGE_AFTER_CANCELLATION dispute:
- explain that the subscription had already been cancelled
- identify the later charge
- request a refund of the full post-cancellation charge

Rules:
- Never invent evidence.
- Never invent IDs, dates, amounts or merchant policies.
- Reference only the information explicitly provided.
- Use plain, professional language suitable for merchant support.
- Return only the dispute message in structured form.
"""


dispute_agent = Agent(
    model=MODEL_ID,
    system_prompt=SYSTEM_PROMPT,
    callback_handler=None,
)


def prepare_dispute(
    case_id: str,
    merchant_id: str,
    merchant_name: str,
    user_id: str,
    transaction_id: str,
    claim_type: Literal[
        "price_hike",
        "duplicate_charge",
        "charge_after_cancellation",
        "other",
    ],
    expected_amount_usd: float,
    actual_amount_usd: float,
    requested_amount_usd: float,
    currency: str,
    anomaly_reason: str,
    evidence: list[EvidenceItem],
) -> DisputeResult:

    evidence_text = "\n".join(
        (
            f"- Type: {item.type}\n"
            f"  Description: {item.description}\n"
            f"  URI: {item.uri}"
        )
        for item in evidence
    )

    prompt = f"""
Merchant name:
{merchant_name}

Transaction ID:
{transaction_id}

Claim type:
{claim_type}

Expected amount:
${expected_amount_usd:.2f}

Actual amount:
${actual_amount_usd:.2f}

Requested refund:
${requested_amount_usd:.2f}

Currency:
{currency}

Anomaly analysis:
{anomaly_reason}

Available evidence:
{evidence_text}

Write the dispute message.

Important:
The requested refund is already calculated and validated.
Do not change it.

For duplicate_charge, the requested refund represents
the full duplicated transaction amount.
"""

    result = dispute_agent(
        prompt,
        structured_output_model=DisputeMessageResult,
    )

    message_result = result.structured_output

    # Contract-critical values are constructed deterministically
    # by Python rather than generated by the LLM.
    return DisputeResult(
        case_id=case_id,
        merchant_id=merchant_id,
        user_id=user_id,
        transaction_id=transaction_id,
        claim_type=claim_type,
        requested_amount_usd=round(
            requested_amount_usd,
            2,
        ),
        currency=currency,
        message=message_result.message,
        evidence=evidence,
    )


if __name__ == "__main__":
    # CASO 2: Spotify duplicate charge

    evidence = [
        EvidenceItem(
            type="transaction_history",
            uri=None,
            description=(
                "Transaction txn_0043 charged $10.99 USD "
                "for Spotify at 08:30 UTC on 2026-08-21."
            ),
        ),
        EvidenceItem(
            type="transaction_history",
            uri=None,
            description=(
                "Transaction txn_0044 charged another "
                "$10.99 USD for the same Spotify subscription "
                "at 08:32 UTC on 2026-08-21, only "
                "120 seconds after txn_0043."
            ),
        ),
    ]

    result = prepare_dispute(
        case_id="case_demo_002",
        merchant_id="mrc_spotify",
        merchant_name="Spotify",
        user_id="usr_demo",
        transaction_id="txn_0044",
        claim_type="duplicate_charge",
        expected_amount_usd=10.99,
        actual_amount_usd=10.99,
        requested_amount_usd=10.99,
        currency="USD",
        anomaly_reason=(
            "A second Spotify charge of $10.99 was posted "
            "only two minutes after another $10.99 charge "
            "for the same subscription."
        ),
        evidence=evidence,
    )

    print(result)